pdadd: pdadd.cpp diary.cpp
	g++ -g -c pdadd.cpp
	g++ -g -c diary.cpp
	g++ -g -o pdadd $^
pdshow: pdshow.cpp diary.cpp
	g++ -g -c pdshow.cpp
	g++ -g -c diary.cpp
	g++ -g -o pdshow $^
pdlist: pdlist.cpp diary.cpp
	g++ -g -c pdlist.cpp
	g++ -g -c diary.cpp
	g++ -g -o pdlist $^
pdremove: pdremove.cpp diary.cpp
	g++ -g -c pdremove.cpp
	g++ -g -c diary.cpp
	g++ -g -o pdremove $^
c: 
	rm diarytemp.txt